export { default as HeaderComponent } from './HeaderComponent.vue'
export { default as HeroComponent } from './HeroComponent.vue'
export { default as ServicesComponent } from './ServicesComponent.vue'
export { default as AboutComponent } from './AboutComponent.vue'
export { default as ProjectsComponent } from './ProjectsComponent.vue'
export { default as TestimonialComponent } from './TestimonialComponent.vue'